export const NOTIFICATION_TYPE = {
	OPEN_NOTIFICATION_DESCRIPTION: 'OPEN_NOTIFICATION_DESCRIPTION',
	CLOSE_NOTIFICATION_DESCRIPTION: 'CLOSE_NOTIFICATION_DESCRIPTION',
	OPEN_DRAWER: 'OPEN_DRAWER',
	CLOSE_DRAWER: 'CLOSE_DRAWER',
};

export const LEFT_TAB_APP_TYPE = {
	LEFT_TAB_ITEM_PRESS: 'LEFT_TAB_ITEM_PRESS',
	RESET_LEFT_APP_TAB_ITEM: 'RESET_LEFT_APP_TAB_ITEM',
};

export const SYS_TYPE = {
	ON_SET_PROGRESS: 'ON_SET_PROGRESS',
	ON_RESET_PROGRESS: 'ON_RESET_PROGRESS',
	ON_DONE_SYS: 'ON_DONE_SYS',
};
