export const OPPORTUNITY_ACTIVE_ID = 'OPPORTUNITY_ACTIVE_ID';
export const RELOAD_CLUE = 'RELOAD_CLUE';
export const SAVE_TEMP_CUSTOMER_INFO = 'SAVE_TEMP_CUSTOMER_INFO';
export const CLEAR_TEMP_CUSTOMER_INFO = 'CLEAR_TEMP_CUSTOMER_INFO';
