export default {
	success: true,
	errorCode: 200,
	errorMsg: 'Lấy danh sách HDBH của HrisCode: MB00008014 thành công!',
	errorDesc: null,
	insuranceContract: [
		{
			contractNumber: '179000101183',
			customerName: 'Nguyễn Thị Nga',
			nationalId: '32A093043494',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '30-07-2019',
			contractStatus: 'Active',
			cIFNumber: '1991936',
			ackDate: '08-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '55',
					insuranceFees: '10.300.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '1.026.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '674.000',
				},
			],
		},
		{
			contractNumber: '179000101607',
			customerName: 'Đỗ Ngọc Sơn',
			nationalId: '337000644753',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '02-08-2019',
			contractStatus: 'Active',
			cIFNumber: '802109',
			ackDate: '23-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '51',
					insuranceFees: '20.000.000',
				},
			],
		},
		{
			contractNumber: '179000103028',
			customerName: 'Đào Xuân Tuấn',
			nationalId: '07003883',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '09-08-2019',
			contractStatus: 'Active',
			cIFNumber: '213851',
			ackDate: '23-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '62',
					insuranceFees: '9.343.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '657.000',
				},
			],
		},
		{
			contractNumber: '179000102820',
			customerName: 'Đinh Chính Việt Anh',
			nationalId: '32A093034488',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '09-08-2019',
			contractStatus: 'Active',
			cIFNumber: '2340435',
			ackDate: '15-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '72',
					insuranceFees: '14.311.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '689.000',
				},
			],
		},
		{
			contractNumber: '179000102663',
			customerName: 'Nguyễn Văn Phấn',
			nationalId: '168575172',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '07-08-2019',
			contractStatus: 'Active',
			cIFNumber: null,
			ackDate: '15-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '61',
					insuranceFees: '13.750.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '649.000',
				},
			],
		},
		{
			contractNumber: '179000105516',
			customerName: 'Nguyễn Văn Đệ',
			nationalId: '33A861123830',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '26-08-2019',
			contractStatus: 'Active',
			cIFNumber: '802155',
			ackDate: '31-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '49',
					insuranceFees: '10.000.000',
				},
			],
		},
		{
			contractNumber: '179000105595',
			customerName: 'Lưu Vũ Hùng',
			nationalId: '32A023020492',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '23-08-2019',
			contractStatus: 'Active',
			cIFNumber: '967436',
			ackDate: '29-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '64',
					insuranceFees: '14.303.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '697.000',
				},
			],
		},
		{
			contractNumber: '179000106134',
			customerName: 'Ngô Văn Thăng',
			nationalId: '34A993008015',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '26-08-2019',
			contractStatus: 'Active',
			cIFNumber: '1170317',
			ackDate: '30-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '62',
					insuranceFees: '11.279.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '721.000',
				},
			],
		},
		{
			contractNumber: '179000103591',
			customerName: 'Đỗ Minh Đức',
			nationalId: '031082001742',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '13-08-2019',
			contractStatus: 'Active',
			cIFNumber: null,
			ackDate: '27-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '64',
					insuranceFees: '13.702.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '697.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
			],
		},
		{
			contractNumber: '179000110068',
			customerName: 'Đào Bá Đoàn',
			nationalId: '327509741190',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '12-09-2019',
			contractStatus: 'Active',
			cIFNumber: '967475',
			ackDate: '27-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '56',
					insuranceFees: '14.182.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '818.000',
				},
			],
		},
		{
			contractNumber: '179000103977',
			customerName: 'Phạm Văn Tráng',
			nationalId: '33A961133398',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '22-08-2019',
			contractStatus: 'Active',
			cIFNumber: '1150579',
			ackDate: '17-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '57',
					insuranceFees: '13.539.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '860.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
			],
		},
		{
			contractNumber: '179000100646',
			customerName: 'Phạm Quốc Cần',
			nationalId: '32B981119291',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '29-07-2019',
			contractStatus: 'Active',
			cIFNumber: null,
			ackDate: '22-08-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '60',
					insuranceFees: '13.650.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '686.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '664.000',
				},
			],
		},
		{
			contractNumber: '179000104653',
			customerName: 'Phạm Đức Luyện',
			nationalId: '32A901119034',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '19-08-2019',
			contractStatus: 'Active',
			cIFNumber: '3591410',
			ackDate: '07-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '54',
					insuranceFees: '13.487.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '868.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '645.000',
				},
			],
		},
		{
			contractNumber: '179000108753',
			customerName: 'Trần Văn Thành',
			nationalId: '327209243684',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '05-09-2019',
			contractStatus: 'Active',
			cIFNumber: '332972',
			ackDate: '11-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '53',
					insuranceFees: '11.102.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '898.000',
				},
			],
		},
		{
			contractNumber: '179000108754',
			customerName: 'Lương Thị Thanh Phương',
			nationalId: '33A022042419',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '05-09-2019',
			contractStatus: 'Active',
			cIFNumber: '202417',
			ackDate: '11-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '63',
					insuranceFees: '14.351.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '649.000',
				},
			],
		},
		{
			contractNumber: '179000111883',
			customerName: 'Mai Mạnh Duy',
			nationalId: '328100041665',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '20-09-2019',
			contractStatus: 'Active',
			cIFNumber: '522294',
			ackDate: null,
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '62',
					insuranceFees: '18.060.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '721.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '618.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
			],
		},
		{
			contractNumber: '179000110848',
			customerName: 'Nguyễn Cao Nguyên',
			nationalId: '328500458470',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '18-09-2019',
			contractStatus: 'Active',
			cIFNumber: '2095173',
			ackDate: '24-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '66',
					insuranceFees: '18.061.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '689.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '649.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
			],
		},
		{
			contractNumber: '179000110914',
			customerName: 'Lê Văn Biên',
			nationalId: '33A951124118',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '17-09-2019',
			contractStatus: 'Active',
			cIFNumber: '1220517',
			ackDate: '23-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '56',
					insuranceFees: '11.351.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '649.000',
				},
			],
		},
		{
			contractNumber: '179000106198',
			customerName: 'Bùi Văn Dũng',
			nationalId: '031014212',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '26-08-2019',
			contractStatus: 'Active',
			cIFNumber: '4229260',
			ackDate: '24-09-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '61',
					insuranceFees: '21.087.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '15',
					insuranceFees: '2.210.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '15',
					insuranceFees: '1.703.000',
				},
			],
		},
		{
			contractNumber: '179000114025',
			customerName: 'Bùi Thanh Bình',
			nationalId: '33A001119445',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '30-09-2019',
			contractStatus: 'Active',
			cIFNumber: '802178',
			ackDate: '05-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '63',
					insuranceFees: '11.138.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '653.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '709.000',
				},
			],
		},
		{
			contractNumber: '179000114061',
			customerName: 'Bùi Thanh Bình',
			nationalId: '33A001119445',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '30-09-2019',
			contractStatus: 'Active',
			cIFNumber: '802178',
			ackDate: '05-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '64',
					insuranceFees: '11.079.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '820.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
			],
		},
		{
			contractNumber: '179000115769',
			customerName: 'Phan Trung Tình',
			nationalId: '042068000025',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '08-10-2019',
			contractStatus: 'Active',
			cIFNumber: null,
			ackDate: null,
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '49',
					insuranceFees: '15.000.000',
				},
			],
		},
		{
			contractNumber: '179000109194',
			customerName: 'Dương Văn Khắc',
			nationalId: '121240621',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '12-09-2019',
			contractStatus: 'Active',
			cIFNumber: '1219956',
			ackDate: '07-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '61',
					insuranceFees: '14.266.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '734.000',
				},
			],
		},
		{
			contractNumber: '179000128045',
			customerName: 'Nguyễn Danh Dũng',
			nationalId: '11016418',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '15-10-2019',
			contractStatus: 'Active',
			cIFNumber: '1466238',
			ackDate: null,
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '68',
					insuranceFees: '17.995.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '689.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '602.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '724.000',
				},
			],
		},
		{
			contractNumber: '179000116456',
			customerName: 'Bùi Viết Giang',
			nationalId: '06001432',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '07-10-2019',
			contractStatus: 'Active',
			cIFNumber: '1196757',
			ackDate: '15-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '62',
					insuranceFees: '10.991.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '860.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '649.000',
				},
			],
		},
		{
			contractNumber: '179000116463',
			customerName: 'Bùi Viết Giang',
			nationalId: '06001432',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '07-10-2019',
			contractStatus: 'Active',
			cIFNumber: '1196757',
			ackDate: '15-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '62',
					insuranceFees: '11.143.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '721.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '636.000',
				},
			],
		},
		{
			contractNumber: '179000123357',
			customerName: 'Nguyễn Khoa Trường',
			nationalId: '33A911133808',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '11-10-2019',
			contractStatus: 'Active',
			cIFNumber: '1168026',
			ackDate: null,
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '53',
					insuranceFees: '18.058.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '1.044.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '898.000',
				},
			],
		},
		{
			contractNumber: '179000114135',
			customerName: 'Bùi Thành Hưng',
			nationalId: '037079001302',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '30-09-2019',
			contractStatus: 'Active',
			cIFNumber: '1142229',
			ackDate: '08-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '60',
					insuranceFees: '10.000.000',
				},
			],
		},
		{
			contractNumber: '179000115116',
			customerName: 'Ngô Văn Thức',
			nationalId: '45A083021932',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '02-10-2019',
			contractStatus: 'Active',
			cIFNumber: '1617404',
			ackDate: '10-10-2019',
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '71',
					insuranceFees: '13.710.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '689.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '12',
					insuranceFees: '601.000',
				},
			],
		},
		{
			contractNumber: '179000126388',
			customerName: 'Phạm Văn Đức',
			nationalId: '328600541669',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '22-10-2019',
			contractStatus: 'Active',
			cIFNumber: '967441',
			ackDate: null,
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '67',
					insuranceFees: '9.311.000',
				},
				{
					productName: 'Hospital Surgical Cash Rider',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '10',
					insuranceFees: '689.000',
				},
			],
		},
		{
			contractNumber: '179000132208',
			customerName: 'Đào Văn Sự',
			nationalId: '13A901030109',
			insuranceContractType: 'MBAL Universal Life',
			issuedDate: '22-10-2019',
			contractStatus: 'Active',
			cIFNumber: '1142267',
			ackDate: null,
			saleChannel: 'Ca Nhan',
			reverseDate: null,
			isVisible: false,
			insuranceContractDetail: [
				{
					productName: 'MBAL Universal Life',
					paymentFrequencyFee: '01 Annually',
					feeTerm: '52',
					insuranceFees: '20.010.000',
				},
			],
		},
	],
	fromDate: '23-07-2019',
	toDate: '23-10-2019',
	employeeID: 'MB00008014',
};
