import {PADDING_COMMON, BOTTOM_WIDTH_SIZE} from 'contants/themes/size';
import {SHALLOW_STYLE} from 'contants/themes';
import {WIDTH_SCREEN} from 'utils/util';
import themes from 'assets/themes';
const paddingVerticalHeader = 10;
const headerPaddingLeft = 10;
const marginSpacing = 30;

export default {
	dropUp: {
		width: 13,
		height: 13,
		marginLeft: 10,
	},
	unCheck: {
		width: 19,
		height: 18,
		backgroundColor: themes.getColor('grayLight'),
		marginLeft: 2,
		marginTop: 3,
	},
	itemFilterHeader: {
		color: themes.getColor('mainColor'),
		maxWidth: 100,
	},
	viewRowButtonFilterClear: {
		backgroundColor: themes.getColor('white'),
		flexDirection: 'row',
		justifyContent: 'flex-end',
		alignItems: 'flex-start',
		height: 60,
	},
	buttonClearFilter: {
		flexDirection: 'row',
		marginRight: 15,
		borderRadius: 5,
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderColor: themes.getColor('grayBold'),
		borderWidth: 1,
	},
	buttonFilter: {
		flexDirection: 'row',
		backgroundColor: themes.getColor('mainColor'),
		marginRight: 15,
		borderRadius: 5,
		paddingHorizontal: 20,
		paddingVertical: 10,
	},
	image: {marginRight: 10, width: 16, height: 16},
	nameFilterHideShow: {
		position: 'absolute',
		top: -10,
		left: 12,
		backgroundColor: themes.getColor('white'),
		zIndex: 1,
		paddingRight: 30,
		paddingLeft: 5,
	},
	buttonDone: {
		width: 130,
		height: 40,
		backgroundColor: themes.getColor('mainColor'),
		borderRadius: 5,
	},
	viewWrapFilter: {
		flexDirection: 'row',
		justifyContent: 'space-around',
		alignItems: 'center',
		marginHorizontal: 10,
		height: 50,
	},
	cancelCardFilter: {
		alignSelf: 'flex-end',
		marginTop: 5,
		marginRight: 10,
	},
	viewSmallCardFilter: {
		flex: 1,
		borderRadius: 10,
		margin: PADDING_COMMON,
		...SHALLOW_STYLE,
	},
	viewBigCardFilter: {
		width: '100%',
		height: 60,
		borderColor: themes.getColor('grayLight'),
		borderRightWidth: 0.5,
	},
	CheckBox: {marginRight: 10},
	threeDot: {tintColor: themes.getColor('blackLight')},
	viewItemHeader: {
		flexDirection: 'row',
		flex: 1,
		justifyContent: 'flex-start',
		paddingLeft: headerPaddingLeft,
		borderRightColor: themes.getColor('grayLight'),
	},
	itemFilter: {flexDirection: 'row', marginHorizontal: 10},
	container: {
		backgroundColor: themes.getColor('white'),
	},
	headerSection: {
		flexDirection: 'row',
		borderTopWidth: 0.5,
		borderBottomWidth: 0.5,
		borderColor: themes.getColor('grayLight'),
		height: 50,
		backgroundColor: themes.getColor('background'),
		alignItems: 'center',
	},
	imageMinus: {tintColor: themes.getColor('grayBold'), marginHorizontal: 10},
	imageSearch: {
		tintColor: themes.getColor('blackBold'),
		marginHorizontal: 15,
		width: 25,
		height: 25,
	},
	imageAdd: {
		borderRadius: 0,
		marginHorizontal: 10,
		width: 25,
		height: 25,
	},
	textSectionHeaderStyle: {
		textAlignVertical: 'center',
		color: themes.getColor('mainColor'),
	},
	textSearch: {
		borderBottomColor: themes.getColor('grayLight'),
		borderBottomWidth: 0.5,
		marginBottom: 5,
		width: 160,
		padding: 0,
		paddingLeft: 10,
		height: 30,
	},
	header: {
		flexDirection: 'row',
		borderTopWidth: 0.5,
		borderColor: themes.getColor('grayLight'),
		height: 40,
	},
	ranker: {
		width: 65,
		height: 20,
		borderRadius: 20,
		borderWidth: 0.5,
		borderColor: themes.getColor('red'),
		backgroundColor: themes.getColor('backgroundRed'),
		justifyContent: 'center',
		alignItems: 'center',
		marginHorizontal: 20,
	},
	triggerMenuStatus: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		marginLeft: 10,
		paddingBottom: 5,
		paddingHorizontal: 5,
	},

	item: {
		backgroundColor: '#f9c2ff',
		padding: 20,
		marginVertical: 8,
	},
	title: {
		fontSize: 24,
	},
	table: {
		flexDirection: 'row',
		borderTopWidth: 0.5,
		borderBottomWidth: 0.5,
		borderColor: themes.getColor('grayLight'),
		minHeight: 50,
	},
	leftBagger: {
		flex: 1,
		flexDirection: 'row',
	},
	viewBagger: {
		flexDirection: 'row',
		flex: 1,
	},
	viewOptionControl: {
		flex: 1,
		flexDirection: 'row',
	},
	numberOptionControl: {
		borderRadius: 5,
		justifyContent: 'center',
		alignItems: 'center',
		marginRight: 15,
		width: 120,
		height: 25,
		borderWidth: 1,
		borderColor: themes.getColor('red'),
	},
	viewTitle: {
		flexDirection: 'row',
		paddingHorizontal: PADDING_COMMON,
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingBottom: marginSpacing,
		height: 45,
		backgroundColor: themes.getColor('white'),
	},
	viewFilter: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	rowFilter: {
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
		marginLeft: 10,
		paddingBottom: 5,
		paddingHorizontal: 5,
		borderBottomColor: themes.getColor('grayLight'),
		borderBottomWidth: 1,
	},
	rowFilterHideShow: {
		borderColor: themes.getColor('grayBold'),
		borderWidth: 1,
		height: 50,
		width:
			(WIDTH_SCREEN - BOTTOM_WIDTH_SIZE - 2 * PADDING_COMMON - 150) / 4,
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderRadius: 5,
	},
	triggerElementHideShow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		height: 30,
	},
	iconDropDown: {
		width: 15,
		height: 15,
		marginLeft: 10,
		tintColor: themes.getColor('blackLight'),
	},
	textItemRowProps: {
		numberOfLines: 2,
		ellipsizeMode: 'tail',
	},
};
