import {WIDTH_SCREEN} from 'utils/util';

export const BOTTOM_WIDTH_SIZE = 60;
export const SCREEN_WIDTH_DIV_3 = WIDTH_SCREEN / 3;
export const PADDING_DRAWER = 16;
export const PADDING_COMMON = 16;

export const BODY_APP_WITH = WIDTH_SCREEN - PADDING_COMMON - BOTTOM_WIDTH_SIZE;
export const HEADER_SPACING_ELEMENT = 50;
//Notification

//Sale kit
const SCREEN_WIDTH_SCALE = 907;
const MENU_WIDTH_SCALE = 201,
	SUB_MENU_WIDTH_SCALE = 156;
const DETAIL_WIDTH_SCALE = 907 - (MENU_WIDTH_SCALE + SUB_MENU_WIDTH_SCALE);
export const SALE_KIT = {
	MENU: MENU_WIDTH_SCALE / SCREEN_WIDTH_SCALE,
	SUB_MENU: SUB_MENU_WIDTH_SCALE / SCREEN_WIDTH_SCALE,
	DETAIL: DETAIL_WIDTH_SCALE / SCREEN_WIDTH_SCALE,
	IMAGE_MAX_SIZE_WEB_VIEW:
		(DETAIL_WIDTH_SCALE / SCREEN_WIDTH_SCALE) * BODY_APP_WITH,
};

//HEDDER

export const HEADER = {
	LOGO: {
		width: 30,
		height: 30,
	},
};
