export const CUSTOMER_DETAIL_SEARCH_CHANGE_BASIC_DATA =
	'CUSTOMER/DETAIL/SEARCH/CUSTOMER_DETAIL_SEARCH_CHANGE_BASIC_DATA';

export const CUSTOMER_DETAIL_SEARCH_CHANGE_EXPERIENCE_STATUS =
	'CUSTOMER/DETAIL/SEARCH/CUSTOMER_DETAIL_SEARCH_CHANGE_EXPERIENCE_STATUS';

export const CUSTOMER_DETAIL_SEARCH_TABLE_POSITION_ADD_ROW =
	'CUSTOMER_DETAIL_SEARCH_TABLE_POSITION_ADD_ROW';
export const CUSTOMER_DETAIL_SEARCH_TABLE_POSITION_MINUS_ROWS =
	'CUSTOMER_DETAIL_SEARCH_TABLE_POSITION_MINUS_ROWS';

export const CUSTOMER_DETAIL_SEARCH_TABLE_POSITION_EDIT_ROWS =
	'CUSTOMER_DETAIL_SEARCH_TABLE_POSITION_EDIT_ROWS';

export const CUSTOMER_DETAIL_SEARCH_STORE_DATA =
	'CUSTOMER_DETAIL_SEARCH_STORE_DATA';

export const CUSTOMER_DETAIL_SEARCH_SET_DATA =
	'CUSTOMER_DETAIL_SEARCH_SET_DATA';
